### ISSUE TITLE
Non-existent modules on the Internet

### ISSUE THREAD

**Issue by toenuff** [Morgan-Stanley/treadmill#10]
When running nosetests as outlined by issue #5, the following modules do not seem to exist.  They are likely internal modules that should either be removed or bundled with Treadmill:

webauthd
proiddb
plugins.fs

The following is the trail of errors illustrating which tests are picking these up:

ERROR: Tests optional container features.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/tome/treadmill/tests/appmgr/manifest_test.py", line 266, in test__add_features
    treadmill.appmgr.manifest._add_features(manifest)
  File "/home/tome/treadmill/lib/python/treadmill/appmgr/manifest.py", line 188, in _add_features
    raise Exception('Unsupported feature: ' + feature)
Exception: Unsupported feature: webauthd
-------------------- >> begin captured logging << --------------------
treadmill.appmgr.manifest: ERROR: Unable to load feature: webauthd
Traceback (most recent call last):
  File "/home/tome/treadmill/lib/python/treadmill/appmgr/manifest.py", line 183, in _add_features
    'treadmill.appmgr.features.' + feature
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named webauthd
--------------------- >> end captured logging << ---------------------

======================================================================
ERROR: Test the normalization of manifests.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/mock/mock.py", line 1297, in patched
    arg = patching.__enter__()
  File "/usr/local/lib/python2.7/dist-packages/mock/mock.py", line 1353, in __enter__
    self.target = self.getter()
  File "/usr/local/lib/python2.7/dist-packages/mock/mock.py", line 1523, in <lambda>
    getter = lambda: _importer(target)
  File "/usr/local/lib/python2.7/dist-packages/mock/mock.py", line 1210, in _importer
    thing = _dot_lookup(thing, comp, import_path)
  File "/usr/local/lib/python2.7/dist-packages/mock/mock.py", line 1199, in _dot_lookup
    __import__(import_path)
ImportError: No module named proiddb

======================================================================
ERROR: Test AppMgr environment initialization.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/mock/mock.py", line 1305, in patched
    return func(*args, **keywargs)
  File "/home/tome/treadmill/tests/appmgr_test.py", line 67, in test_initialize
    app_init.initialize(self.app_env)
  File "/home/tome/treadmill/lib/python/treadmill/appmgr/initialize.py", line 16, in initialize
    nodeinit.initialize(tm_env)
  File "/home/tome/treadmill/lib/python/treadmill/osmodules/linux/nodeinit.py", line 20, in initialize
    fs.init_plugins(tm_env.root)
  File "/home/tome/treadmill/lib/python/treadmill/fs.py", line 253, in init_plugins
    for mod in _iter_plugins():
  File "/home/tome/treadmill/lib/python/treadmill/fs.py", line 235, in _iter_plugins
    fsplugins = importlib.import_module('treadmill.plugins.fs')
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named plugins.fs

**Comment by snyaggarwal** [comment]
apiproxy module is also missing:

======================================================================
ERROR: Failure: ImportError (cannot import name apiproxy)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/centos/treadmill/.tox/py27/lib/python2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/home/centos/treadmill/.tox/py27/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/home/centos/treadmill/.tox/py27/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/centos/treadmill/tests/sproc/apiproxy_test.py", line 11, in <module>
    from treadmill.sproc import apiproxy
ImportError: cannot import name apiproxy
