### ISSUE TITLE
jsonpointer needs to support versions .7 and up

### ISSUE THREAD

**Issue by toenuff** [Morgan-Stanley/treadmill#4]
Modern versions of jsonpointer do not have set_pointer() method.  When running through the tests, I'm getting the following error:

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/mock/mock.py", line 1305, in patched
    return func(*args, **keywargs)
  File "/home/tome/treadmill/tests/api/schema_test.py", line 318, in test_allocation
    _ok(api.create, 'aaa/prod', _patch(good, '/environment', 'qa'))
  File "/home/tome/treadmill/tests/api/schema_test.py", line 46, in _patch
    return jsonpointer.set_pointer(obj, jsonptr, value, inplace=False)
AttributeError: 'module' object has no attribute 'set_pointer'

I cannot downgrade jsonpointer.  It looks like we need to support newer versions.  I found this bit of code that has a fix to update set_pointer() in some other project that is using this:
https://github.com/peritus/robotframework-httplibrary/commit/aa838096072be97ce5fd3744a989b7b59b4fb9ca

**Comment by toenuff** [comment]
My mistake - v 1.10 of jsonpointer fixes the issue.  You must do a pip install jsonpointer --upgrade in order to fix this.

Updated #5 to reflect this - closing this issue
