### ISSUE TITLE
utils_test failure

### ISSUE THREAD

**Issue by toenuff** [Morgan-Stanley/treadmill#9]
When running nosetests as outlined in Issue #5, I am getting the following error:

======================================================================
ERROR: Tests conversion of values into human readable format.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/tome/treadmill/tests/utils_test.py", line 233, in test_humanreadable
    self.assertEquals('2,310', utils.cpu_to_readable(2310))
  File "/home/tome/treadmill/lib/python/treadmill/utils.py", line 348, in cpu_to_readable
    locale.setlocale(locale.LC_ALL, 'en_US')
  File "/usr/lib/python2.7/locale.py", line 579, in setlocale
    return _setlocale(category, locale)
Error: unsupported locale setting

**Comment by toenuff** [comment]
Updated Issue #5 with fix - just need to manually add the en_US locale.  By default, only en_US-utf8 is installed.
